apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels: 
        app: fakeshop
    spec:
      containers:
      - name: fakeshop
        image: eloirmagalhaes/fakeshop:v1
        ports: 
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  selector: 
    app: fakeshop
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort


